[platformio]
src_dir = main

[env:papers3_single_shot_bootloader]
platform = espressif32
board = esp32-s3-devkitm-1
framework = espidf
board_build.partitions = partitions.csv
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
build_flags =
	-I../../include
